### ISSUE TITLE
suggestion (sorry this package is just really cool and I've thought about this being a thing before)

### ISSUE THREAD

**Issue by Vertacyl** [TheEnderek0/Endereks-Custom-Entrances#1]
Is it possible to give the players more control over the test chamber screen (for the number system) so it doesn't just display the name and random number of the test chamber?
So many things were hard coded for some reason

**Comment by TheEnderek0** [comment]
Sorry taking so long to respond.
Unfortunatelly that is hardcoded, so I can't change that
